## 🤔 유닛 테스트

- 유닛 테스트를 진행해야 되는 이유
    - 메서드에 독립적으로 테스트를 하기 때문에 빠른 리펙토링 반영과 테스트를 진행할 수 있습니다.
    - 코드의 확장이나 리펙토링 사이에도 안정성을 확보한 채로 대응 가능합니다.
    
- 유닛 테스트를 진행하는 방법
    - 유닛 테스트는 기본적으로 개발자가 예상한 값과 실제 동작한 결과를 비교하는 방식으로 작성됩니다.
    
    ```swift
    func testArraySorting() {
        let input = [1, 7, 6, 3, 10]
        let expectation = [1, 3, 6, 7, 10]
        let result = input.sorted()
        // XCTAssertEqual은 값이 같은지를 비교하는 메서드
        XCTAssertEqual(result, expectation)
    }
    ```
    

- 테스트가 가능한 코드란?
    - 말 그대로 테스트가 가능한 코드를 작성하는것을 말합니다.
    - 의존성이 너무 강한 메서드는 외부 코드의 영향을 많이 받게되어 테스트하기 어렵습니다.
    - 통제된 환경에서 테스트가 가능한 코드를 테스트가 가능한 코드라고 합니다.

## 🤔 FIRST 원칙

- `Fast`테스트는 빠르게 동작할 수 있어야 합니다. 실제 프로젝트에서는 수많은 테스트 코드를 작성하게 될 텐데 테스트가 느리게 동작한다면 테스트를 실행하는 데에만 몇 분의 시간이 소요될 것입니다. 테스트 코드는 빠르게 확인하고, 수정하고 반영하는 데에 큰 의미가 있기 때문에 속도가 느린 테스트는 테스트 코드의 의미 중 많은 부분을 잃어버린 것과 같다고 볼 수 있습니다.
- `Independent/Isolated`
    
    각각의 테스트는 서로 독립적이며 서로 의존해서는 안 됩니다. 좋은 단위 테스트는 최소한의 단위의 테스트에 집중할 수 있게 각 테스트들이 서로에게 영향을 주어서는 안됩니다. 만약 다른 코드에 의존성이 높거나 영향을 많이 주고받고 있는 경우에는 완전히 통제된 상황에서 테스트를 진행하기 어려울 수 있으며 테스트가 실패하게 되었을 경우 그 원인이 불분명한 경우가 발생할 수 있습니다.
    
- `Repeatable`
    
    테스트는 언제 어디서나 같은 결과가 반복되어야 합니다. 즉 모든 환경을 통제하여 매번 예상한 결과대로 테스트가 진행되게 해야 합니다. 이를 위해서 통제가 어려운 부분에 대해서는 **테스트를 위한 객체**를 만들어주는 방법을 선택하기도 합니다.
    
- `Self-Validating`
    
    테스트는 Bool을 이용하여 성공/실패에 대해서 스스로 검증이 가능해야 합니다. 테스트 코드 내부에서 이 테스트가 잘 동작했는지를 판별할 수 있어야 합니다.
    
- `Timely`
    
    이상적인 테스트는 테스트하려는 실제 코드를 구현하기 직전에 구현해야 합니다. 만약 실제 코드를 구현한 후에 테스트 코드를 작성할 경우 테스트하기가 매우 까다롭거나 불가능하도록 설계가 되어있을 지도 모릅니다
    

## 🤔 프로젝트 생성시 테스트 코드 생성 하는 방법

- 프로젝트 생성시에 아래 화면과 같이 `include Tests` 항목을 체크해주면 생성시 테스트 코드 unit test, ui test가 함께 생성된다.

- 유닛 테스트 동작 순서 
    - `setUpWithError` : 테스트 코드를 초기화 시켜주는 함수
    - `testExampleCode` : 사용자가 테스트 하고자 하는 유닛 테스트 실행 함수
    - `tearDownWithError` : 테스트 코드를 빈값으로 변경하는 코드
- `testExampleCode`는 함수의 네이밍이 test이어야 네이밍 거터를 띄울수 있음
<img src="https://github.com/rohhyungwoo/ARAD_Public/assets/67363759/ad723799-cb66-4af3-966c-e6468cd4d59c" width="600" height="150"/>

- 유닛 테스트 구현 예시
    - `LottoMachine` 클래스를 `setUpWithError`를 통해 초기화
    - `testCountMatchingNumber`를 실행하고 `XCTAssert` 메서드를 사용
    - 사용자의 예상 결과 값, 프로그램의 실제 결과 값을 비교
    - `XCTAssertThrowsError`와 같이 다양한 유닛 테스트용 메서드가 존재함

```swift
var sut: LottoMachine!

override func setUpWithError() throws {
    sut = LottoMachine()
}

override func tearDownWithError() throws {
    sut = nil
}

func testCountMatchingNumber() {
    let userInput = [1,2,3]
    let winnerInput = [1,2,3]
    var result: Int
    do {
        result = try sut.countMatchingNumber(user:userInput, winner: winnerInput)
        XCTAssertThrowsError(result)
    } catch {
        XCTAssertEqual(error as? LottoMachineError, LottoMachineError.invalidNumbers)
    }
}
```
